baseurl = "http://superlightcarillon.com.s3-website-eu-west-1.amazonaws.com/"
languageCode = "en-us"
title = "Giova sito carillon"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"


[params]
    site_author = "Giovanna Dalla Costa"
    site_description = "The awesome SoftFarm"
    location = "Bassano del Grappa"
    # Link custom assets relative to /static
    avatar = "img/Giovanna_LOGO_piuma.png"
    header_background = "img/Balena_Azzurra_Sotto.jpg"
    header_title = "Soft Farm - Morbidi NannAmici"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Define which content types are shown on the homepage
    mainSections = ["post"]

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = "giova.dallacosta"
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = "superlight_soft_farm"
    github    = ""
    gplus     = ""
